
import { DutchTaxDeadline, User, Task, TaskStatus, ChatMessage, TaskTemplate } from './types';

export const MOCK_USERS: User[] = [
  { 
    id: '1', 
    name: 'Anna Kowalska', 
    role: 'Manager', 
    avatar: 'https://picsum.photos/id/101/100/100', 
    email: 'anna.k@boekhouder.nl',
    phone: '+31 6 1234 5678',
    location: 'Rotterdam, NL',
    website: 'www.annak-finance.nl',
    status: 'Online',
    bio: 'Specjalistka ds. podatków międzynarodowych z 10-letnim doświadczeniem. Pomagam firmom w ekspansji na rynek holenderski.'
  },
  { 
    id: '2', 
    name: 'Mehmet Yilmaz', 
    role: 'Accountant', 
    avatar: 'https://picsum.photos/id/102/100/100', 
    email: 'mehmet.y@boekhouder.nl',
    phone: '+31 6 8765 4321',
    location: 'Amsterdam, NL',
    website: 'www.yilmaz-accounting.com',
    status: 'Busy',
    bio: 'Ekspert w zakresie ZZP i MKB. Doradzam w optymalizacji podatkowej dla małych przedsiębiorstw.'
  },
  { 
    id: '3', 
    name: 'Jan Jansen', 
    role: 'Accountant', 
    avatar: 'https://picsum.photos/id/103/100/100', 
    email: 'jan.j@boekhouder.nl',
    phone: '+31 6 1122 3344',
    location: 'Utrecht, NL',
    website: 'www.jansen-advies.nl',
    status: 'Offline',
    bio: 'Gecertificeerd belastingadviseur. Focus op loonadministratie en jaarrekeningen.'
  },
  { 
    id: '4', 
    name: 'Elif Demir', 
    role: 'Admin', 
    avatar: 'https://picsum.photos/id/104/100/100', 
    email: 'elif.d@boekhouder.nl',
    phone: '+31 6 9988 7766',
    location: 'Eindhoven, NL',
    status: 'Online',
    bio: 'Zarządzanie biurem i koordynacja dokumentów. Dbam o to, aby wszystkie terminy były dotrzymane.'
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 't1',
    title: 'BTW Aangifte Q3 - Client X',
    description: 'Prepare VAT return for Client X regarding import from China.',
    assigneeId: '1',
    dueDate: '2023-10-25',
    dueTime: '14:00',
    status: TaskStatus.IN_PROGRESS,
    priority: 'High',
    category: 'Tax',
    estimatedHours: 2.5,
    tags: ['BTW', 'International'],
    attachments: []
  },
  {
    id: 't2',
    title: 'Jaarrekening 2024 preparation',
    description: 'Gather documents for yearly report.',
    assigneeId: '2',
    dueDate: '2023-11-15',
    status: TaskStatus.TODO,
    priority: 'Medium',
    category: 'Audit',
    estimatedHours: 8,
    tags: ['Annual Report'],
    attachments: []
  },
  {
    id: 't3',
    title: 'Loonheffingen August',
    description: 'Check payroll tax calculations.',
    assigneeId: '2',
    dueDate: '2023-09-30',
    dueTime: '09:00',
    status: TaskStatus.DONE,
    priority: 'High',
    category: 'Payroll',
    estimatedHours: 1,
    tags: ['Payroll'],
    attachments: []
  },
];

export const INITIAL_CHAT: ChatMessage[] = [
  { id: 'm1', userId: '1', channelId: 'general', text: 'Cześć wszystkim! Czy raporty VAT są gotowe?', timestamp: new Date(Date.now() - 10000000).toISOString() },
  { id: 'm2', userId: '2', channelId: 'general', text: 'Evet, çoğu tamamlandı. Sadece Client Y kaldı.', timestamp: new Date(Date.now() - 8000000).toISOString() },
  { id: 'm3', userId: '3', channelId: 'btw', text: 'Ik heb een vraag over de KOR regeling.', timestamp: new Date(Date.now() - 5000000).toISOString() },
];

export const DUTCH_TAX_DEADLINES: DutchTaxDeadline[] = [
  { 
    date: '2023-10-31', 
    descriptionPL: 'Termin deklaracji VAT (BTW) za Q3', 
    descriptionTR: '3. Çeyrek KDV (BTW) beyanname son tarihi',
    descriptionNL: 'BTW-aangifte deadline Q3'
  },
  { 
    date: '2023-12-31', 
    descriptionPL: 'Koniec roku finansowego', 
    descriptionTR: 'Mali yıl sonu',
    descriptionNL: 'Einde boekjaar'
  },
  { 
    date: '2024-01-31', 
    descriptionPL: 'Termin deklaracji VAT (BTW) za Q4', 
    descriptionTR: '4. Çeyrek KDV (BTW) beyanname son tarihi',
    descriptionNL: 'BTW-aangifte deadline Q4'
  },
  { 
    date: '2024-04-30', 
    descriptionPL: 'Termin rozliczenia podatku dochodowego (IB)', 
    descriptionTR: 'Gelir vergisi (IB) beyanname son tarihi',
    descriptionNL: 'Inkomstenbelasting (IB) aangifte deadline'
  },
];

export const DICTIONARY = {
  PL: {
    dashboard: 'Pulpit',
    tasks: 'Zadania',
    calendar: 'Kalendarz',
    chat: 'Komunikator',
    documents: 'Dokumenty',
    settings: 'Ustawienia',
    team: 'Drużyna',
    profile: 'Mój Profil',
    new_task: 'Nowe Zadanie',
    edit_task: 'Edytuj Zadanie',
    search: 'Szukaj...',
    todo: 'Do Zrobienia',
    in_progress: 'W Trakcie',
    review: 'Do Sprawdzenia',
    done: 'Zakończone',
    dueDate: 'Termin',
    dueTime: 'Godzina',
    assignee: 'Przypisany',
    priority: 'Priorytet',
    send: 'Wyślij',
    upcoming_deadlines: 'Nadchodzące Terminy (NL)',
    welcome: 'Witaj w Boekhouder Connect',
    users_online: 'Księgowi Online',
    upload_doc: 'Dodaj Dokument',
    my_tasks: 'Moje Zadania',
    all_tasks: 'Wszystkie',
    save_changes: 'Zapisz Zmiany',
    delete_task: 'Usuń Zadanie',
    cancel: 'Anuluj',
    full_name: 'Imię i Nazwisko',
    avatar_url: 'Link do zdjęcia (URL)',
    change_password: 'Zmień Hasło',
    current_password: 'Obecne Hasło',
    new_password: 'Nowe Hasło',
    confirm_password: 'Potwierdź Hasło',
    role: 'Rola',
    contact_email: 'Email Kontaktowy',
    team_members: 'Członkowie Zespołu',
    quick_templates: 'Szybkie Szablony (NL)',
    client_name: 'Nazwa Klienta',
    period: 'Okres',
    year: 'Rok',
    title: 'Tytuł',
    description: 'Opis',
    status: 'Status',
    move_to: 'Przenieś do',
    create_template: 'Zarządzaj Szablonami',
    template_name: 'Nazwa Szablonu',
    template_desc: 'Opis',
    save_template: 'Zapisz Szablon',
    manage_templates: 'Menadżer Szablonów',
    add_new_template: 'Dodaj Nowy Szablon',
    system_template: 'Wszystkie Szablony', 
    custom_template: 'Szablon Własny',
    select_color: 'Wybierz Kolor',
    edit: 'Edytuj',
    delete: 'Usuń',
    // New Form Fields
    category: 'Kategoria',
    estimated_hours: 'Estymowany Czas (h)',
    cat_tax: 'Podatki',
    cat_payroll: 'Kadry/Płace',
    cat_audit: 'Audyt',
    cat_meeting: 'Spotkanie',
    cat_advisory: 'Doradztwo',
    cat_general: 'Ogólne',
    // Attachments
    attachments: 'Załączniki',
    add_attachment: 'Dodaj plik',
    record_voice: 'Nagraj notatkę',
    stop_recording: 'Zatrzymaj',
    recording: 'Nagrywanie...',
    drop_files: 'Upuść pliki tutaj',
    voice_note: 'Notatka Głosowa',
    // Chat Specific
    new_group: 'Nowa Grupa',
    group_name: 'Nazwa Grupy',
    create_group: 'Utwórz Grupę',
    search_messages: 'Szukaj w czacie...',
     // Dashboard Specific
    overdue: 'Przeterminowane',
    high_priority: 'Wysoki Priorytet',
    team_workload: 'Obciążenie Zespołu',
    task_distribution: 'Status Zadań',
    recent_activity: 'Ostatnia Aktywność',
    quick_actions: 'Szybkie Akcje',
    view_calendar: 'Zobacz Kalendarz',
    next_deadline: 'Najbliższy Termin',
    days_left: 'dni do końca',
    // Team Specific
    phone: 'Telefon',
    website: 'Strona WWW',
    location: 'Lokalizacja',
    about: 'O mnie',
    meet_team: 'Poznaj nasz zespół ekspertów księgowych',
    // Settings & Profile
    manage_prefs: 'Zarządzaj ustawieniami aplikacji',
    saved_success: 'Zapisano pomyślnie!',
    general_appearance: 'Ogólne i Wygląd',
    accounting_prefs: 'Preferencje Księgowe',
    notifications: 'Powiadomienia',
    security_privacy: 'Bezpieczeństwo i Prywatność',
    language_select: 'Język / Language / Taal',
    dark_mode: 'Tryb Ciemny',
    compact_mode: 'Tryb Kompaktowy',
    easier_eyes: 'Łagodniejszy dla oczu w nocy',
    more_data: 'Więcej danych na ekranie',
    default_currency: 'Domyślna Waluta',
    fiscal_year: 'Koniec Roku Podatkowego',
    push_notifs: 'Powiadomienia Push',
    push_desc: 'Otrzymuj powiadomienia o przypisanych zadaniach.',
    email_digest: 'Podsumowanie Email',
    email_desc: 'Codzienne podsumowanie terminów i zadań.',
    sound_effects: 'Efekty Dźwiękowe',
    sound_desc: 'Dźwięki dla nowych wiadomości.',
    two_factor: 'Uwierzytelnianie dwuskładnikowe (2FA)',
    two_factor_desc: 'Wymagaj kodu SMS przy logowaniu.',
    session_timeout: 'Wylogowanie po czasie',
    recommendation: 'Rekomendacja',
    enable_2fa: 'Włącz 2FA, aby chronić dane finansowe klientów.',
    basic_info: 'Informacje Podstawowe',
    contact_location: 'Kontakt i Lokalizacja',
    manage_deadlines: 'Zarządzaj pracą i terminami',
    week: 'Tydzień',
    select_week: 'Wybierz Tydzień'
  },
  TR: {
    dashboard: 'Panel',
    tasks: 'Görevler',
    calendar: 'Takvim',
    chat: 'Sohbet',
    documents: 'Belgeler',
    settings: 'Ayarlar',
    team: 'Takım',
    profile: 'Profilim',
    new_task: 'Yeni Görev',
    edit_task: 'Görevi Düzenle',
    search: 'Ara...',
    todo: 'Yapılacaklar',
    in_progress: 'Devam Ediyor',
    review: 'İnceleme',
    done: 'Tamamlandı',
    dueDate: 'Son Tarih',
    dueTime: 'Saat',
    assignee: 'Atanan',
    priority: 'Öncelik',
    send: 'Gönder',
    upcoming_deadlines: 'Yaklaşan Vadeler (NL)',
    welcome: 'Boekhouder Connect\'e Hoşgeldiniz',
    users_online: 'Çevrimiçi Muhasebeciler',
    upload_doc: 'Belge Yükle',
    my_tasks: 'Görevlerim',
    all_tasks: 'Tümü',
    save_changes: 'Değişiklikleri Kaydet',
    delete_task: 'Görevi Sil',
    cancel: 'İptal',
    full_name: 'İsim Soyisim',
    avatar_url: 'Profil Fotoğrafı (URL)',
    change_password: 'Şifre Değiştir',
    current_password: 'Mevcut Şifre',
    new_password: 'Yeni Şifre',
    confirm_password: 'Şifreyi Onayla',
    role: 'Rol',
    contact_email: 'İletişim E-postası',
    team_members: 'Takım Üyeleri',
    quick_templates: 'Hızlı Şablonlar (NL)',
    client_name: 'Müşteri Adı',
    period: 'Dönem',
    year: 'Yıl',
    title: 'Başlık',
    description: 'Açıklama',
    status: 'Durum',
    move_to: 'Şuraya taşı',
    create_template: 'Şablonları Yönet',
    template_name: 'Şablon Adı',
    template_desc: 'Açıklama',
    save_template: 'Şablonu Kaydet',
    manage_templates: 'Şablon Yöneticisi',
    add_new_template: 'Yeni Şablon Ekle',
    system_template: 'Tüm Şablonlar', 
    custom_template: 'Özel Şablon',
    select_color: 'Renk Seç',
    edit: 'Düzenle',
    delete: 'Sil',
    // New Form Fields
    category: 'Kategori',
    estimated_hours: 'Tahmini Süre (s)',
    cat_tax: 'Vergi',
    cat_payroll: 'Bordro',
    cat_audit: 'Denetim',
    cat_meeting: 'Toplantı',
    cat_advisory: 'Danışmanlık',
    cat_general: 'Genel',
    // Attachments
    attachments: 'Ekler',
    add_attachment: 'Dosya Ekle',
    record_voice: 'Ses Kaydet',
    stop_recording: 'Durdur',
    recording: 'Kaydediliyor...',
    drop_files: 'Dosyaları buraya bırakın',
    voice_note: 'Sesli Not',
    // Chat Specific
    new_group: 'Yeni Grup',
    group_name: 'Grup Adı',
    create_group: 'Grup Oluştur',
    search_messages: 'Sohbette ara...',
     // Dashboard Specific
    overdue: 'Gecikmiş',
    high_priority: 'Yüksek Öncelik',
    team_workload: 'Takım İş Yükü',
    task_distribution: 'Görev Dağılımı',
    recent_activity: 'Son Etkinlik',
    quick_actions: 'Hızlı İşlemler',
    view_calendar: 'Takvimi Görüntüle',
    next_deadline: 'Sıradaki Vade',
    days_left: 'gün kaldı',
    // Team Specific
    phone: 'Telefon',
    website: 'Web Sitesi',
    location: 'Konum',
    about: 'Hakkımda',
    meet_team: 'Muhasebe uzman ekibimizle tanışın',
    // Settings & Profile
    manage_prefs: 'Uygulama ayarlarını yönetin',
    saved_success: 'Başarıyla kaydedildi!',
    general_appearance: 'Genel ve Görünüm',
    accounting_prefs: 'Muhasebe Tercihleri',
    notifications: 'Bildirimler',
    security_privacy: 'Güvenlik ve Gizlilik',
    language_select: 'Dil / Language / Taal',
    dark_mode: 'Karanlık Mod',
    compact_mode: 'Kompakt Mod',
    easier_eyes: 'Geceleri gözler için daha rahat',
    more_data: 'Ekranda daha fazla veri',
    default_currency: 'Varsayılan Para Birimi',
    fiscal_year: 'Mali Yıl Sonu',
    push_notifs: 'Anlık Bildirimler',
    push_desc: 'Size görev atandığında bildirim alın.',
    email_digest: 'E-posta Özeti',
    email_desc: 'Vadelerin ve görevlerin günlük özeti.',
    sound_effects: 'Ses Efektleri',
    sound_desc: 'Yeni mesajlar için sesler.',
    two_factor: 'İki Faktörlü Kimlik Doğrulama (2FA)',
    two_factor_desc: 'Girişte SMS kodu iste.',
    session_timeout: 'Oturum Zaman Aşımı',
    recommendation: 'Öneri',
    enable_2fa: 'Müşteri finansal verilerini korumak için 2FA\'yı etkinleştirin.',
    basic_info: 'Temel Bilgiler',
    contact_location: 'İletişim ve Konum',
    manage_deadlines: 'İşleri ve vadeleri yönetin',
    week: 'Hafta',
    select_week: 'Hafta Seç'
  },
  NL: {
    dashboard: 'Dashboard',
    tasks: 'Taken',
    calendar: 'Kalender',
    chat: 'Chat',
    documents: 'Documenten',
    settings: 'Instellingen',
    team: 'Team',
    profile: 'Mijn Profiel',
    new_task: 'Nieuwe Taak',
    edit_task: 'Taak Bewerken',
    search: 'Zoeken...',
    todo: 'Te Doen',
    in_progress: 'Bezig',
    review: 'Nazien',
    done: 'Klaar',
    dueDate: 'Deadline',
    dueTime: 'Tijd',
    assignee: 'Toegewezen aan',
    priority: 'Prioriteit',
    send: 'Verstuur',
    upcoming_deadlines: 'Komende Deadlines (NL)',
    welcome: 'Welkom bij Boekhouder Connect',
    users_online: 'Boekhouders Online',
    upload_doc: 'Upload Document',
    my_tasks: 'Mijn Taken',
    all_tasks: 'Alle',
    save_changes: 'Wijzigingen Opslaan',
    delete_task: 'Taak Verwijderen',
    cancel: 'Annuleren',
    full_name: 'Volledige Naam',
    avatar_url: 'Profielfoto (URL)',
    change_password: 'Wachtwoord Wijzigen',
    current_password: 'Huidig Wachtwoord',
    new_password: 'Nieuw Wachtwoord',
    confirm_password: 'Bevestig Wachtwoord',
    role: 'Rol',
    contact_email: 'Contact E-mail',
    team_members: 'Teamleden',
    quick_templates: 'Snelle Sjablonen (NL)',
    client_name: 'Klantnaam',
    period: 'Periode',
    year: 'Jaar',
    title: 'Titel',
    description: 'Omschrijving',
    status: 'Status',
    move_to: 'Verplaats naar',
    create_template: 'Sjablonen Beheren',
    template_name: 'Sjabloonnaam',
    template_desc: 'Omschrijving',
    save_template: 'Sjabloon Opslaan',
    manage_templates: 'Sjabloonbeheer',
    add_new_template: 'Nieuw Sjabloon Toevoegen',
    system_template: 'Alle Sjablonen',
    custom_template: 'Aangepast Sjabloon',
    select_color: 'Kies Kleur',
    edit: 'Bewerken',
    delete: 'Verwijderen',
    // New Form Fields
    category: 'Categorie',
    estimated_hours: 'Geschatte Uren',
    cat_tax: 'Belasting',
    cat_payroll: 'Salaris',
    cat_audit: 'Audit',
    cat_meeting: 'Vergadering',
    cat_advisory: 'Advies',
    cat_general: 'Algemeen',
    // Attachments
    attachments: 'Bijlagen',
    add_attachment: 'Bestand Toevoegen',
    record_voice: 'Spraaknotitie',
    stop_recording: 'Stoppen',
    recording: 'Opnemen...',
    drop_files: 'Bestanden hier neerzetten',
    voice_note: 'Spraaknotitie',
    // Chat Specific
    new_group: 'Nieuwe Groep',
    group_name: 'Groepsnaam',
    create_group: 'Groep Maken',
    search_messages: 'Zoek in chat...',
     // Dashboard Specific
    overdue: 'Te Laat',
    high_priority: 'Hoge Prioriteit',
    team_workload: 'Teamwerkbelasting',
    task_distribution: 'Taakverdeling',
    recent_activity: 'Recente Activiteit',
    quick_actions: 'Snelle Acties',
    view_calendar: 'Bekijk Kalender',
    next_deadline: 'Volgende Deadline',
    days_left: 'dagen over',
    // Team Specific
    phone: 'Telefoon',
    website: 'Website',
    location: 'Locatie',
    about: 'Over mij',
    meet_team: 'Ontmoet ons team van boekhoudkundige experts',
    // Settings & Profile
    manage_prefs: 'Beheer applicatievoorkeuren',
    saved_success: 'Succesvol opgeslagen!',
    general_appearance: 'Algemeen & Uiterlijk',
    accounting_prefs: 'Boekhoudkundige Voorkeuren',
    notifications: 'Meldingen',
    security_privacy: 'Beveiliging & Privacy',
    language_select: 'Taal / Language / Język',
    dark_mode: 'Donkere Modus',
    compact_mode: 'Compacte Modus',
    easier_eyes: 'Rustiger voor de ogen \'s nachts',
    more_data: 'Meer gegevens op het scherm',
    default_currency: 'Standaard Valuta',
    fiscal_year: 'Einde Boekjaar',
    push_notifs: 'Pushmeldingen',
    push_desc: 'Ontvang meldingen bij toegewezen taken.',
    email_digest: 'E-mail Samenvatting',
    email_desc: 'Dagelijks overzicht van deadlines.',
    sound_effects: 'Geluidseffecten',
    sound_desc: 'Geluiden voor nieuwe berichten.',
    two_factor: 'Tweefactorauthenticatie (2FA)',
    two_factor_desc: 'Vereis SMS-code bij inloggen.',
    session_timeout: 'Sessie Time-out',
    recommendation: 'Aanbeveling',
    enable_2fa: 'Schakel 2FA in om financiële klantgegevens te beschermen.',
    basic_info: 'Basisinformatie',
    contact_location: 'Contact & Locatie',
    manage_deadlines: 'Beheer werk en deadlines',
    week: 'Week',
    select_week: 'Selecteer Week'
  }
};

export const TASK_TEMPLATES: TaskTemplate[] = [
  {
    id: 'sys-btw',
    label: 'BTW (VAT)',
    color: 'bg-blue-100 text-blue-700 border-blue-200',
    title: 'BTW Aangifte',
    descPL: 'Przygotowanie i wysłanie deklaracji VAT (Omzetbelasting). Sprawdź faktury zakupu i sprzedaży.',
    descTR: 'KDV beyannamesinin (Omzetbelasting) hazırlanması ve gönderilmesi. Alış ve satış faturalarını kontrol edin.',
    descNL: 'Voorbereiden en indienen van de BTW-aangifte (Omzetbelasting). Controleer inkoop- en verkoopfacturen.',
    priority: 'High',
    category: 'Tax'
  },
  {
    id: 'sys-icp',
    label: 'ICP (UE)',
    color: 'bg-indigo-100 text-indigo-700 border-indigo-200',
    title: 'ICP Opgaaf',
    descPL: 'Deklaracja transakcji wewnątrzwspólnotowych (Intra-Community). Wymagana przy eksporcie usług/towarów do UE.',
    descTR: 'Topluluk İçi İşlemler (Intra-Community) beyannamesi. AB\'ye hizmet/mal ihracatında gereklidir.',
    descNL: 'Opgaaf Intracommunautaire Prestaties (ICP). Vereist bij export van diensten/goederen binnen de EU.',
    priority: 'Medium',
    category: 'Tax'
  },
  {
    id: 'sys-loon',
    label: 'Loon (Payroll)',
    color: 'bg-green-100 text-green-700 border-green-200',
    title: 'Loonheffingen',
    descPL: 'Miesięczne rozliczenie podatku od wynagrodzeń. Sprawdź paski wypłat (Loonstroken).',
    descTR: 'Aylık bordro vergisi beyannamesi. Maaş bordrolarını (Loonstroken) kontrol edin.',
    descNL: 'Maandelijkse aangifte Loonheffingen. Controleer de loonstroken.',
    priority: 'High',
    category: 'Payroll'
  },
  {
    id: 'sys-ib',
    label: 'IB (PIT)',
    color: 'bg-orange-100 text-orange-700 border-orange-200',
    title: 'Inkomstenbelasting',
    descPL: 'Rozliczenie roczne podatku dochodowego. Sprawdź: Hypotheekrenteaftrek, Toeslagen, ZZP aftrek.',
    descTR: 'Yıllık gelir vergisi beyannamesi. Kontrol: Mortgage faiz indirimi, Ödenekler, ZZP indirimi.',
    descNL: 'Aangifte Inkomstenbelasting. Check: Hypotheekrenteaftrek, Toeslagen, Zelfstandigenaftrek.',
    priority: 'Medium',
    category: 'Tax'
  },
  {
    id: 'sys-vpb',
    label: 'VPB (CIT)',
    color: 'bg-purple-100 text-purple-700 border-purple-200',
    title: 'Vennootschapsbelasting',
    descPL: 'Podatek korporacyjny dla B.V. Wymagana bilans i rachunek zysków i strat.',
    descTR: 'B.V. için kurumlar vergisi. Bilanço ve kar/zarar hesabı gereklidir.',
    descNL: 'Aangifte Vennootschapsbelasting voor B.V. Balans en winst-en-verliesrekening vereist.',
    priority: 'Low',
    category: 'Audit'
  }
];
